image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

# start up tasks
tasks:
  # init: Will be executed one time when creating a workspace, command: will be exected each time you open workspace
  - init: |
      echo "Build knowage server..."
      cd Knowage-Server-Docker
      mkdir resources
      docker-compose build
    command: |
      echo "Running Knowage server... (connect with user: biadmin, pwd: biadmin)"
      docker-compose up
  - command: gp await-port 8080 && gp preview "$(gp url 8080)/knowage"

# Clone knowage:
# git clone --depth 1 https://github.com/KnowageLabs/Knowage-Server.git
