version: "3"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:6.4
    depends_on:
      - knowagedb
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_DB=$DB_DB
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
  
  knowagedb:
    image: mysql:5.6
    environment:
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_DB
      - MYSQL_ROOT_PASSWORD=knowagerootpassword
    networks:
      - main
    volumes:
      - "db:/var/lib/mysql"
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e "SELECT 1"
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db:

networks:
  main:

