version: "3"
services:
  knowage:
    image: knowagelabs/knowage-server-docker:develop
    depends_on:
      - knowagedb
    ports:
      - "8080:8080"
    env_file:
      - env-variables.env
    networks:
      - main
  
  knowagedb:
    image: mysql:5.6
    env_file:
      - env-variables.env
    networks:
      - main
    volumes:
      - "db:/var/lib/mysql"
    healthcheck:
      test: mysql --user=$$DB_USER --password=$$DB_PASS -e "SELECT 1"
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db:

networks:
  main:

